### ISSUE TITLE
Question sur ton module pronote.

### ISSUE THREAD

**Issue by tet102** [bugsounet/MMM-Pronote#2]
Bonjour bugsounet.
Je suis tombé sur ton module qui est en cours de developppement et je trouve cela génial car j'ai 2 enfants et tous les soirs c'est devant écran pour voir les devoirs à faire.
Perso, je fais afficher le soir Pronote via le module I-FRAME-ping qui ouvre une fenêtre navigateur et je trouve cela top car pas de codage à faire mais le souci c'est le mot de passe à rentrer à chaque fois.
Donc bonne idée de dedveloppper un module.
J'ai hate de tester ton module et tu as une idée de date sur sortie de ton module ?
Merci par avance...Cdlt

**Comment by bugsounet** [comment]
Bonsoir, oui le module est prêt pour faire une bêta.
Il faudrait que je termine le wiki.
J essai de faire cela rapidement !

Le module devais être déjà dispos dimanche dernier ! J ai une presque une semaine de retard...

J' essai de faire au mieux ;)

**Comment by tet102** [comment]
C'est pas grave...c'est juste que c'est super intéressant et une bonne
nouvelle pour les fans de Pronote 😂 encore merci

**Comment by bugsounet** [comment]
Plus d info et screen shot [ici] (https://forum.magicmirror.builders/topic/13572/fr-only-mmm-pronote?page=1)

**Comment by bugsounet** [comment]
Le module est pret pour une version Beta
